I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/man.rpy", line 298, in script
    $ stress_org += 1
  File "game/man.rpy", line 298, in <module>
    $ stress_org += 1
NameError: name 'stress_org' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/man.rpy", line 298, in script
    $ stress_org += 1
  File "C:\Users\Пользователь1\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Пользователь1\Desktop\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/man.rpy", line 298, in <module>
    $ stress_org += 1
NameError: name 'stress_org' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
The sound of cicades 1.0
Fri May 31 13:07:28 2024
